name: paramag
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - snakemake
  - spades
  - maxbin2
  - busco
  - mafft
  - trimal
  - iqtree
  - raxml
  - blobtoolkit
  - fastqc
  - trimmomatic