name: paramag
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - snakemake
  - fastqc
  - trimmomatic
  - spades
  - maxbin2
  - busco
  - mafft
  - trimal
  - iqtree
  - blast
  - java-jdk  # For ASTRAL
  - pandas  # Required for Python scripting in Snakemake
  - matplotlib  # For optional plotting
  - tqdm  # For progress bars (optional)

